export const GET_HOME_PROPERTY = 'GET_HOME_PROPERTY';
export const GET_HOME_PROPERTY_STARTED = 'GET_HOME_PROPERTY_STARTED';
export const GET_HOME_PROPERTY_ERROR = 'GET_HOME_PROPERTY_ERROR';

export const HOME_SEARCH_INPUT_CHANGE = 'HOME_SEARCH_INPUT_CHANGE';

export const GET_HOME_LOCATION_SEARCH = 'GET_HOME_LOCATION_SEARCH';
export const GET_HOME_LOCATION_SEARCH_STARTED =
  'GET_HOME_LOCATION_SEARCH_STARTED';
export const GET_HOME_LOCATION_SEARCH_ERROR = 'GET_HOME_LOCATION_SEARCH_ERROR';
