export const GET_HOME_PROPERTY = 'GET_HOME_PROPERTY';
export const GET_HOME_PROPERTY_STARTED = 'GET_HOME_PROPERTY_STARTED';
export const GET_HOME_PROPERTY_ERROR = 'GET_HOME_PROPERTY_ERROR';

export const HOME_SEARCH_INPUT_CHANGE = 'HOME_SEARCH_INPUT_CHANGE';

export const GET_HOME_LOCATION_SEARCH = 'GET_HOME_LOCATION_SEARCH';
export const GET_HOME_LOCATION_SEARCH_STARTED =
  'GET_HOME_LOCATION_SEARCH_STARTED';
export const GET_HOME_LOCATION_SEARCH_ERROR = 'GET_HOME_LOCATION_SEARCH_ERROR';

export const GET_HOME_FEATURED = 'GET_HOME_FEATURED';
export const GET_HOME_FEATURED_STARTED = 'GET_HOME_FEATURED_STARTED';
export const GET_HOME_FEATURED_ERROR = 'GET_HOME_FEATURED_ERROR';

export const GET_HOME_LUXURY = 'GET_HOME_LUXURY';
export const GET_HOME_LUXURY_STARTED = 'GET_HOME_LUXURY_STARTED';
export const GET_HOME_LUXURY_ERROR = 'GET_HOME_LUXURY_ERROR';

export const GET_BUY_PROPERTY = 'GET_BUY_PROPERTY';
export const GET_BUY_PROPERTY_STARTED = 'GET_BUY_PROPERTY_STARTED';
export const GET_BUY_PROPERTY_ERROR = 'GET_BUY_PROPERTY_ERROR';
export const ON_CHANGE_BUY_PROPERTY_INPUT = 'ON_CHANGE_BUY_PROPERTY_INPUT';

export const GET_RENT_PROPERTY = 'GET_RENT_PROPERTY';
export const GET_RENT_PROPERTY_STARTED = 'GET_RENT_PROPERTY_STARTED';
export const GET_RENT_PROPERTY_ERROR = 'GET_RENT_PROPERTY_ERROR';

export const ADMIN_LOGIN_STARTED = 'ADMIN_LOGIN_STARTED';
export const ADMIN_LOGGED_IN = 'ADMIN_LOGGED_IN';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';

export const GET_ADMIN_PROPERTY = 'GET_ADMIN_PROPERTY';
export const GET_ADMIN_PROPERTY_STARTED = 'GET_ADMIN_PROPERTY_STARTED';
export const GET_ADMIN_PROPERTY_ERROR = 'GET_ADMIN_PROPERTY_ERROR';

export const UPLOAD_IMAGE_STARTED = 'UPLOAD_IMAGE_STARTED';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const CLEAR_UPLOAD = 'CLEAR_UPLOAD';

export const ADMIN_PROPERTY_INPUT_CHANGE = 'ADMIN_PROPERTY_INPUT_CHANGE';

export const ADD_ADMIN_PROPERTY = 'ADD_ADMIN_PROPERTY';
export const ADD_ADMIN_PROPERTY_STARTED = 'ADD_ADMIN_PROPERTY_STARTED';
export const ADD_ADMIN_PROPERTY_ERROR = 'ADD_ADMIN_PROPERTY_ERROR';

export const GET_AGENT_PROPERTY = 'GET_AGENT_PROPERTY';
export const GET_AGENT_PROPERTY_ERROR = 'GET_AGENT_PROPERTY_ERROR';
export const GET_AGENT_PROPERTY_STARTED = 'GET_AGENT_PROPERTY_STARTED ';

export const GET_PROPERTY_BY_ID = 'GET_PROPERTY_BY_ID';
export const GET_PROPERTY_BY_ID_STARTED = 'GET_PROPERTY_BY_ID_STARTED';
export const GET_PROPERTY_BY_ID_ERROR = 'GET_PROPERTY_BY_ID_ERROR';

export const CHANGE_HOME_PROPERTY_PAGE = 'CHANGE_HOME_PROPERTY_PAGE';
export const CHANGE_HOME_FEATURED_PAGE = 'CHANGE_HOME_FEATURED_PAGE';
export const CHANGE_HOME_LUXURY_PAGE = 'CHANGE_HOME_LUXURY_PAGE';

export const GET_AMENITY_PROPERTY = 'GET_AMENITY_PROPERTY';
export const GET_AMENITY_PROPERTY_ERROR = 'GET_AMENITY_PROPERTY_ERROR';
export const GET_AMENITY_PROPERTY_STARTED = 'GET_AMENITY_PROPERTY_STARTED ';

export const EDIT_ADMIN_PROPERTY = 'EDIT_ADMIN_PROPERTY';
export const EDIT_ADMIN_PROPERTY_STARTED = 'EDIT_ADMIN_PROPERTY_STARTED';
export const EDIT_ADMIN_PROPERTY_ERROR = 'EDIT_ADMIN_PROPERTY_ERROR';

export const GET_ADMIN_PROPERTY_BY_ID = 'GET_ADMIN_PROPERTY_BY_ID';
export const GET_ADMIN_PROPERTY_BY_ID_STARTED =
  'GET_ADMIN_PROPERTY_BY_ID_STARTED';
export const GET_ADMIN_PROPERTY_BY_ID_ERROR = 'GET_ADMIN_PROPERTY_BY_ID_ERROR';

export const DELETE_ADMIN_PROPERTY = 'DELETE_ADMIN_PROPERTY';
export const DELETE_ADMIN_PROPERTY_STARTED = 'DELETE_ADMIN_PROPERTY_STARTED';
export const DELETE_ADMIN_PROPERTY_ERROR = 'DELETE_ADMIN_PROPERTY_ERROR';

export const CLEAR_ADD_PROPERTY = 'CLEAR_ADD_PROPERTY';

export const ADD_ADMIN_AGENCY = 'ADD_ADMIN_AGENCY';
export const ADD_ADMIN_AGENCY_ERROR = 'ADD_ADMIN_AGENCY_ERROR';
export const ADD_ADMIN_AGENCY_STARTED = 'ADD_ADMIN_AGENCY_STARTED';
export const ADMIN_AGENCY_INPUT_CHANGE = 'ADMIN_AGENCY_INPUT_CHANGE';
export const EDIT_ADMIN_AGENCY = 'EDIT_ADMIN_AGENCY';
export const EDIT_ADMIN_AGENCY_ERROR = 'EDIT_ADMIN_AGENCY_ERROR';
export const EDIT_ADMIN_AGENCY_STARTED = 'EDIT_ADMIN_AGENCY_STARTED';
export const GET_ADMIN_AGENCY_BY_ID = 'GET_ADMIN_AGENCY_BY_ID';
export const GET_ADMIN_AGENCY_BY_ID_ERROR = 'GET_ADMIN_AGENCY_BY_ID_ERROR';
export const GET_ADMIN_AGENCY_BY_ID_STARTED = 'GET_ADMIN_AGENCY_BY_ID_STARTED';
export const CLEAR_ADD_AGENCY = 'CLEAR_ADD_AGENCY';

export const GET_ADMIN_AGENCY = 'GET_ADMIN_AGENCY';
export const GET_ADMIN_AGENCY_STARTED = 'GET_ADMIN_AGENCY_STARTED';
export const GET_ADMIN_AGENCY_ERROR = 'GET_ADMIN_AGENCY_ERROR';

export const DELETE_ADMIN_AGENCY = 'DELETE_ADMIN_AGENCY';
export const DELETE_ADMIN_AGENCY_STARTED = 'DELETE_ADMIN_AGENCY_STARTED';
export const DELETE_ADMIN_AGENCY_ERROR = 'DELETE_ADMIN_AGENCY_ERROR';

export const GET_ADMIN_AGENCY_AGENT = 'GET_ADMIN_AGENCY_AGENT';
export const GET_ADMIN_AGENCY_AGENT_STARTED = 'GET_ADMIN_AGENCY_AGENT_STARTED';
export const GET_ADMIN_AGENCY_AGENT_ERROR = 'GET_ADMIN_AGENCY_AGENT_ERROR';

export const GET_ADMIN_AGENT_BY_ID = 'GET_ADMIN_AGENT_BY_ID';
export const GET_ADMIN_AGENT_BY_ID_STARTED = 'GET_ADMIN_AGENT_BY_ID_STARTED';
export const GET_ADMIN_AGENT_BY_ID_ERROR = 'GET_ADMIN_AGENT_BY_ID_ERROR';
export const ADMIN_AGENT_INPUT_CHANGE = 'ADMIN_AGENT_INPUT_CHANGE';

export const ADD_ADMIN_AGENT = 'ADD_ADMIN_AGENT';
export const ADD_ADMIN_AGENT_STARTED = 'ADD_ADMIN_AGENT_STARTED';
export const ADD_ADMIN_AGENT_ERROR = 'ADD_ADMIN_AGENT_ERROR';

export const EDIT_ADMIN_AGENT_STARTED = 'EDIT_ADMIN_AGENT_STARTED';
export const EDIT_ADMIN_AGENT = 'EDIT_ADMIN_AGENT';
export const EDIT_ADMIN_AGENT_ERROR = 'EDIT_ADMIN_AGENT_ERROR';

export const DELETE_ADMIN_AGENT = 'DELETE_ADMIN_AGENT';
export const DELETE_ADMIN_AGENT_STARTED = 'DELETE_ADMIN_AGENT_STARTED';
export const DELETE_ADMIN_AGENT_ERROR = 'DELETE_ADMIN_AGENT_ERROR';

export const GET_AMENITY_ADMIN = 'GET_AMENITY_ADMIN';
export const GET_AMENITY_ADMIN_STARTED = 'GET_AMENITY_ADMIN_STARTED';
export const GET_AMENITY_ADMIN_ERROR = 'GET_AMENITY_ADMIN_ERROR';

export const ADMIN_AMENITY_INPUT_CHANGE = 'ADMIN_AMENITY_INPUT_CHANGE';
export const ADD_ADMIN_AMENITY_STARTED = 'ADD_ADMIN_AMENITY_STARTED';
export const ADD_ADMIN_AMENITY_ERROR = 'ADD_ADMIN_AMENITY_ERROR';
export const ADD_ADMIN_AMENITY = 'ADD_ADMIN_AMENITY';

export const EDIT_ADMIN_AMENITY = 'EDIT_ADMIN_AMENITY';
export const EDIT_ADMIN_AMENITY_STARTED = 'EDIT_ADMIN_AMENITY_STARTED';
export const EDIT_ADMIN_AMENITY_ERROR = 'EDIT_ADMIN_AMENITY_ERROR';

export const GET_AMENITY_ADMIN_BY_ID = 'GET_AMENITY_ADMIN_BY_ID';
export const GET_AMENITY_ADMIN_STARTED_BY_ID =
  'GET_AMENITY_ADMIN_STARTED_BY_ID';
export const GET_AMENITY_ADMIN_ERROR_BY_ID = 'GET_AMENITY_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_AMENITY = 'CLEAR_ADD_AMENITY';
export const DELETE_ADMIN_AMENITY_STARTED = 'DELETE_ADMIN_AMENITY_STARTED';
export const DELETE_ADMIN_AMENITY_ERROR = 'DELETE_ADMIN_AMENITY_ERROR';
export const DELETE_ADMIN_AMENITY = 'DELETE_ADMIN_AMENITY';

export const GET_NEIGHBORHOOD_PROPERTY = 'GET_NEIGHBORHOOD_PROPERTY';
export const GET_NEIGHBORHOOD_PROPERTY_STARTED =
  'GET_NEIGHBORHOOD_PROPERTY_STARTED';
export const GET_NEIGHBORHOOD_PROPERTY_ERROR =
  'GET_NEIGHBORHOOD_PROPERTY_ERROR';

export const GET_NEIGHBORHOOD_ADMIN = 'GET_NEIGHBORHOOD_ADMIN';
export const GET_NEIGHBORHOOD_ADMIN_STARTED = 'GET_NEIGHBORHOOD_ADMIN_STARTED';
export const GET_NEIGHBORHOOD_ADMIN_ERROR = 'GET_NEIGHBORHOOD_ADMIN_ERROR';

export const ADMIN_NEIGHBORHOOD_INPUT_CHANGE =
  'ADMIN_NEIGHBORHOOD_INPUT_CHANGE';
export const ADD_ADMIN_NEIGHBORHOOD_STARTED = 'ADD_ADMIN_NEIGHBORHOOD_STARTED';
export const ADD_ADMIN_NEIGHBORHOOD_ERROR = 'ADD_ADMIN_NEIGHBORHOOD_ERROR';
export const ADD_ADMIN_NEIGHBORHOOD = 'ADD_ADMIN_NEIGHBORHOOD';

export const EDIT_ADMIN_NEIGHBORHOOD = 'EDIT_ADMIN_NEIGHBORHOOD';
export const EDIT_ADMIN_NEIGHBORHOOD_STARTED =
  'EDIT_ADMIN_NEIGHBORHOOD_STARTED';
export const EDIT_ADMIN_NEIGHBORHOOD_ERROR = 'EDIT_ADMIN_NEIGHBORHOOD_ERROR';

export const GET_NEIGHBORHOOD_ADMIN_BY_ID = 'GET_NEIGHBORHOOD_ADMIN_BY_ID';
export const GET_NEIGHBORHOOD_ADMIN_STARTED_BY_ID =
  'GET_NEIGHBORHOOD_ADMIN_STARTED_BY_ID';
export const GET_NEIGHBORHOOD_ADMIN_ERROR_BY_ID =
  'GET_NEIGHBORHOOD_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_NEIGHBORHOOD = 'CLEAR_ADD_NEIGHBORHOOD';
export const DELETE_ADMIN_NEIGHBORHOOD_STARTED =
  'DELETE_ADMIN_NEIGHBORHOOD_STARTED';
export const DELETE_ADMIN_NEIGHBORHOOD_ERROR =
  'DELETE_ADMIN_NEIGHBORHOOD_ERROR';
export const DELETE_ADMIN_NEIGHBORHOOD = 'DELETE_ADMIN_NEIGHBORHOOD';

export const GET_TAGLINE_PROPERTY = 'GET_TAGLINE_PROPERTY';
export const GET_TAGLINE_PROPERTY_STARTED = 'GET_TAGLINE_PROPERTY_STARTED';
export const GET_TAGLINE_PROPERTY_ERROR = 'GET_TAGLINE_PROPERTY_ERROR';

export const GET_TAGHEAD_ADMIN = 'GET_TAGHEAD_ADMIN';
export const GET_TAGHEAD_ADMIN_STARTED = 'GET_TAGHEAD_ADMIN_STARTED';
export const GET_TAGHEAD_ADMIN_ERROR = 'GET_TAGHEAD_ADMIN_ERROR';

export const ADMIN_TAGHEAD_INPUT_CHANGE = 'ADMIN_TAGHEAD_INPUT_CHANGE';
export const ADD_ADMIN_TAGHEAD_STARTED = 'ADD_ADMIN_TAGHEAD_STARTED';
export const ADD_ADMIN_TAGHEAD_ERROR = 'ADD_ADMIN_TAGHEAD_ERROR';
export const ADD_ADMIN_TAGHEAD = 'ADD_ADMIN_TAGHEAD';

export const EDIT_ADMIN_TAGHEAD = 'EDIT_ADMIN_TAGHEAD';
export const EDIT_ADMIN_TAGHEAD_STARTED = 'EDIT_ADMIN_TAGHEAD_STARTED';
export const EDIT_ADMIN_TAGHEAD_ERROR = 'EDIT_ADMIN_TAGHEAD_ERROR';

export const GET_TAGHEAD_ADMIN_BY_ID = 'GET_TAGHEAD_ADMIN_BY_ID';
export const GET_TAGHEAD_ADMIN_STARTED_BY_ID =
  'GET_TAGHEAD_ADMIN_STARTED_BY_ID';
export const GET_TAGHEAD_ADMIN_ERROR_BY_ID = 'GET_TAGHEAD_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_TAGHEAD = 'CLEAR_ADD_TAGHEAD';
export const DELETE_ADMIN_TAGHEAD_STARTED = 'DELETE_ADMIN_TAGHEAD_STARTED';
export const DELETE_ADMIN_TAGHEAD_ERROR = 'DELETE_ADMIN_TAGHEAD_ERROR';
export const DELETE_ADMIN_TAGHEAD = 'DELETE_ADMIN_TAGHEAD';

export const GET_TAGLINE_ADMIN = 'GET_TAGLINE_ADMIN';
export const GET_TAGLINE_ADMIN_STARTED = 'GET_TAGLINE_ADMIN_STARTED';
export const GET_TAGLINE_ADMIN_ERROR = 'GET_TAGLINE_ADMIN_ERROR';

export const ADMIN_TAGLINE_INPUT_CHANGE = 'ADMIN_TAGLINE_INPUT_CHANGE';
export const ADD_ADMIN_TAGLINE_STARTED = 'ADD_ADMIN_TAGLINE_STARTED';
export const ADD_ADMIN_TAGLINE_ERROR = 'ADD_ADMIN_TAGLINE_ERROR';
export const ADD_ADMIN_TAGLINE = 'ADD_ADMIN_TAGLINE';

export const EDIT_ADMIN_TAGLINE = 'EDIT_ADMIN_TAGLINE';
export const EDIT_ADMIN_TAGLINE_STARTED = 'EDIT_ADMIN_TAGLINE_STARTED';
export const EDIT_ADMIN_TAGLINE_ERROR = 'EDIT_ADMIN_TAGLINE_ERROR';

export const GET_TAGLINE_ADMIN_BY_ID = 'GET_TAGLINE_ADMIN_BY_ID';
export const GET_TAGLINE_ADMIN_STARTED_BY_ID =
  'GET_TAGLINE_ADMIN_STARTED_BY_ID';
export const GET_TAGLINE_ADMIN_ERROR_BY_ID = 'GET_TAGLINE_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_TAGLINE = 'CLEAR_ADD_TAGLINE';
export const DELETE_ADMIN_TAGLINE_STARTED = 'DELETE_ADMIN_TAGLINE_STARTED';
export const DELETE_ADMIN_TAGLINE_ERROR = 'DELETE_ADMIN_TAGLINE_ERROR';
export const DELETE_ADMIN_TAGLINE = 'DELETE_ADMIN_TAGLINE';

export const GET_TAGHEAD_TAGLINE = 'GET_TAGHEAD_TAGLINE';
export const GET_TAGHEAD_TAGLINE_STARTED = 'GET_TAGHEAD_TAGLINE_STARTED';
export const GET_TAGHEAD_TAGLINE_ERROR = 'GET_TAGHEAD_TAGLINE_ERROR';

export const GET_NEWSTOPICS_ADMIN = 'GET_NEWSTOPICS_ADMIN';
export const GET_NEWSTOPICS_ADMIN_STARTED = 'GET_NEWSTOPICS_ADMIN_STARTED';
export const GET_NEWSTOPICS_ADMIN_ERROR = 'GET_NEWSTOPICS_ADMIN_ERROR';

export const ADMIN_NEWSTOPICS_INPUT_CHANGE = 'ADMIN_NEWSTOPICS_INPUT_CHANGE';
export const ADD_ADMIN_NEWSTOPICS_STARTED = 'ADD_ADMIN_NEWSTOPICS_STARTED';
export const ADD_ADMIN_NEWSTOPICS_ERROR = 'ADD_ADMIN_NEWSTOPICS_ERROR';
export const ADD_ADMIN_NEWSTOPICS = 'ADD_ADMIN_NEWSTOPICS';

export const EDIT_ADMIN_NEWSTOPICS = 'EDIT_ADMIN_NEWSTOPICS';
export const EDIT_ADMIN_NEWSTOPICS_STARTED = 'EDIT_ADMIN_NEWSTOPICS_STARTED';
export const EDIT_ADMIN_NEWSTOPICS_ERROR = 'EDIT_ADMIN_NEWSTOPICS_ERROR';

export const GET_NEWSTOPICS_ADMIN_BY_ID = 'GET_NEWSTOPICS_ADMIN_BY_ID';
export const GET_NEWSTOPICS_ADMIN_STARTED_BY_ID =
  'GET_NEWSTOPICS_ADMIN_STARTED_BY_ID';
export const GET_NEWSTOPICS_ADMIN_ERROR_BY_ID =
  'GET_NEWSTOPICS_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_NEWSTOPICS = 'CLEAR_ADD_NEWSTOPICS';
export const DELETE_ADMIN_NEWSTOPICS_STARTED =
  'DELETE_ADMIN_NEWSTOPICS_STARTED';
export const DELETE_ADMIN_NEWSTOPICS_ERROR = 'DELETE_ADMIN_NEWSTOPICS_ERROR';
export const DELETE_ADMIN_NEWSTOPICS = 'DELETE_ADMIN_NEWSTOPICS';

export const GET_NEWS_ADMIN = 'GET_NEWS_ADMIN';
export const GET_NEWS_ADMIN_STARTED = 'GET_NEWS_ADMIN_STARTED';
export const GET_NEWS_ADMIN_ERROR = 'GET_NEWS_ADMIN_ERROR';

export const ADMIN_NEWS_INPUT_CHANGE = 'ADMIN_NEWS_INPUT_CHANGE';
export const ADD_ADMIN_NEWS_STARTED = 'ADD_ADMIN_NEWS_STARTED';
export const ADD_ADMIN_NEWS_ERROR = 'ADD_ADMIN_NEWS_ERROR';
export const ADD_ADMIN_NEWS = 'ADD_ADMIN_NEWS';

export const EDIT_ADMIN_NEWS = 'EDIT_ADMIN_NEWS';
export const EDIT_ADMIN_NEWS_STARTED = 'EDIT_ADMIN_NEWS_STARTED';
export const EDIT_ADMIN_NEWS_ERROR = 'EDIT_ADMIN_NEWS_ERROR';

export const GET_NEWS_ADMIN_BY_ID = 'GET_NEWS_ADMIN_BY_ID';
export const GET_NEWS_ADMIN_STARTED_BY_ID = 'GET_NEWS_ADMIN_STARTED_BY_ID';
export const GET_NEWS_ADMIN_ERROR_BY_ID = 'GET_NEWS_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_NEWS = 'CLEAR_ADD_NEWS';
export const DELETE_ADMIN_NEWS_STARTED = 'DELETE_ADMIN_NEWS_STARTED';
export const DELETE_ADMIN_NEWS_ERROR = 'DELETE_ADMIN_NEWS_ERROR';
export const DELETE_ADMIN_NEWS = 'DELETE_ADMIN_NEWS';

export const GET_TOPICS_NEWS = 'GET_TOPICS_NEWS';
export const GET_TOPICS_NEWS_STARTED = 'GET_TOPICS_NEWS_STARTED';
export const GET_TOPICS_NEWS_ERROR = 'GET_TOPICS_NEWS_ERROR';

export const GET_BLOG_ADMIN = 'GET_BLOG_ADMIN';
export const GET_BLOG_ADMIN_STARTED = 'GET_BLOG_ADMIN_STARTED';
export const GET_BLOG_ADMIN_ERROR = 'GET_BLOG_ADMIN_ERROR';

export const ADMIN_BLOG_INPUT_CHANGE = 'ADMIN_BLOG_INPUT_CHANGE';
export const ADD_ADMIN_BLOG_STARTED = 'ADD_ADMIN_BLOG_STARTED';
export const ADD_ADMIN_BLOG_ERROR = 'ADD_ADMIN_BLOG_ERROR';
export const ADD_ADMIN_BLOG = 'ADD_ADMIN_BLOG';

export const EDIT_ADMIN_BLOG = 'EDIT_ADMIN_BLOG';
export const EDIT_ADMIN_BLOG_STARTED = 'EDIT_ADMIN_BLOG_STARTED';
export const EDIT_ADMIN_BLOG_ERROR = 'EDIT_ADMIN_BLOG_ERROR';

export const GET_BLOG_ADMIN_BY_ID = 'GET_BLOG_ADMIN_BY_ID';
export const GET_BLOG_ADMIN_STARTED_BY_ID = 'GET_BLOG_ADMIN_STARTED_BY_ID';
export const GET_BLOG_ADMIN_ERROR_BY_ID = 'GET_BLOG_ADMIN_ERROR_BY_ID';

export const CLEAR_ADD_BLOG = 'CLEAR_ADD_BLOG';
export const DELETE_ADMIN_BLOG_STARTED = 'DELETE_ADMIN_BLOG_STARTED';
export const DELETE_ADMIN_BLOG_ERROR = 'DELETE_ADMIN_BLOG_ERROR';
export const DELETE_ADMIN_BLOG = 'DELETE_ADMIN_BLOG';

export const GET_BUY_LOCATION_SEARCH = 'GET_BUY_LOCATION_SEARCH';
export const GET_BUY_LOCATION_SEARCH_STARTED =
  'GET_BUY_LOCATION_SEARCH_STARTED';
export const GET_BUY_LOCATION_SEARCH_ERROR = 'GET_BUY_LOCATION_SEARCH_ERROR';

export const ON_CHANGE_RENT_PROPERTY_INPUT = 'ON_CHANGE_RENT_PROPERTY_INPUT';
export const GET_RENT_LOCATION_SEARCH = 'GET_RENT_LOCATION_SEARCH';
export const GET_RENT_LOCATION_SEARCH_STARTED =
  'GET_RENT_LOCATION_SEARCH_STARTED';
export const GET_RENT_LOCATION_SEARCH_ERROR = 'GET_RENT_LOCATION_SEARCH_ERROR';

export const GET_TOPSTORY_WEB = 'GET_TOPSTORY_WEB';
export const GET_TOPSTORY_WEB_STARTED = 'GET_TOPSTORY_WEB_STARTED';
export const GET_TOPSTORY_WEB_ERROR = 'GET_TOPSTORY_WEB_ERROR';

export const GET_TOPSTORY_TOPICS_WEB = 'GET_TOPSTORY_TOPICS_WEB';
export const GET_TOPSTORY_TOPICS_WEB_STARTED =
  'GET_TOPSTORY_TOPICS_WEB_STARTED';
export const GET_TOPSTORY_TOPICS_WEB_ERROR = 'GET_TOPSTORY_TOPICS_WEB_ERROR';

export const GET_SINGLE_NEWS_WEB = 'GET_SINGLE_NEWS_WEB';
export const GET_SINGLE_NEWS_WEB_STARTED = 'GET_SINGLE_NEWS_WEB_STARTED';
export const GET_SINGLE_NEWS_WEB_ERROR = 'GET_SINGLE_NEWS_WEB_ERROR';

export const GET_BLOG_WEB = 'GET_BLOG_WEB';
export const GET_BLOG_WEB_STARTED = 'GET_BLOG_WEB_STARTED';
export const GET_BLOG_WEB_ERROR = 'GET_BLOG_WEB_ERROR';

export const GET_SINGLE_BLOG_WEB = 'GET_SINGLE_BLOG_WEB';
export const GET_SINGLE_BLOG_WEB_STARTED = 'GET_SINGLE_BLOG_WEB_STARTED';
export const GET_SINGLE_BLOG_WEB_ERROR = 'GET_SINGLE_BLOG_WEB_ERROR';

export const GET_CAT_FEATURED = 'GET_CAT_FEATURED';
export const GET_CAT_FEATURED_ERROR = 'GET_CAT_FEATURED_ERROR';
export const GET_CAT_FEATURED_STARTED = 'GET_CAT_FEATURED_STARTED';
export const GET_RTMIN_STARTED = 'GET_RTMIN_STARTED';
export const GET_RTMIN = 'GET_RTMIN';
export const GET_RTMIN_ERROR = 'GET_RTMIN_ERROR';

export const ON_CHANGE_LIST_PAGE_PROPERTY_INPUT =
  ' ON_CHANGE_LIST_PAGE_PROPERTY_INPUT';

export const GET_LISTPROP_LOCATION_SEARCH = 'GET_LISTPROP_LOCATION_SEARCH';
export const GET_LISTPROP_LOCATION_SEARCH_STARTED =
  'GET_LISTPROP_LOCATION_SEARCH_STARTED';
export const GET_LISTPROP_LOCATION_SEARCH_ERROR =
  'GET_LISTPROP_LOCATION_SEARCH_ERROR';
export const GET_NEIGHBORHOOD_WEB = 'GET_NEIGHBORHOOD_WEB';
export const GET_NEIGHBORHOOD_WEB_ERROR = 'GET_NEIGHBORHOOD_WEB_ERROR';
export const GET_NEIGHBORHOOD_WEB_STARTED = 'GET_NEIGHBORHOOD_WEB_STARTED';

export const GET_TAGLINE_WEB = 'GET_TAGLINE_WEB';
export const GET_TAGLINE_WEB_ERROR = 'GET_TAGLINE_WEB_ERROR';
export const GET_TAGLINE_WEB_STARTED = 'GET_TAGLINE_WEB_STARTED';
export const GET_TAGHEAD_WEB = 'GET_TAGHEAD_WEB';
export const GET_TAGHEAD_WEB_ERROR = 'GET_TAGHEAD_WEB_ERROR';
export const GET_TAGHEAD_WEB_STARTED = 'GET_TAGHEAD_WEB_STARTED';

export const GET_LUXURY_VILLA = 'GET_LUXURY_LUXURY';
export const GET_LUXURY_VILLA_STARTED = 'GET_LUXURY_LUXURY_STARTED';
export const GET_LUXURY_VILLA_ERROR = 'GET_LUXURY_LUXURY_ERROR';

export const GET_LUXURY_APPARTMENT = 'GET_LUXURY_APPARTMENT';
export const GET_LUXURY_APPARTMENT_STARTED = 'GET_LUXURY_APPARTMENT_STARTED';
export const GET_LUXURY_APPARTMENT_ERROR = 'GET_LUXURY_APPARTMENT_ERROR';

export const GET_LUXURY_TOWNHOUSE = 'GET_LUXURY_TOWNHOUSE';
export const GET_LUXURY_TOWNHOUSE_STARTED = 'GET_LUXURY_TOWNHOUSE_STARTED';
export const GET_LUXURY_TOWNHOUSE_ERROR = 'GET_LUXURY_TOWNHOUSE_ERROR';

export const GET_LUXURY_PENTHOUSE = 'GET_LUXURY_PENTHOUSE';
export const GET_LUXURY_PENTHOUSE_STARTED = 'GET_LUXURY_PENTHOUSE_STARTED';
export const GET_LUXURY_PENTHOUSE_ERROR = 'GET_LUXURY_PENTHOUSE_ERROR';
